plc/WriteExecutePIB.c

Fix wrong little endian conversion of 16 bit header->PIBLENGTH
amphost terminated with error on a device reset:
root@OpenWrt:/lib/firmware/plc# plctool -i br-lan -R
br-lan 00:B0:52:00:00:01 Reset Device
br-lan BC:F2:AF:ED:36:46 Resetting ...
root@OpenWrt:/lib/firmware/plc# 
br-lan 00:B0:52:00:00:01 Host Action Request is (4) config memory.
br-lan 00:B0:52:00:00:01 Write /lib/firmware/plc/FW0153_FW_V1_MAC-7450-v5.3.1-02-NW6__-X-FINAL.nvm (0) (00000040:18912)
br-lan 00:B0:52:00:00:01 Start /lib/firmware/plc/FW0153_FW_V1_MAC-7450-v5.3.1-02-NW6__-X-FINAL.nvm (0) (000000C0)
br-lan 00:B0:52:00:00:01 Host Action Request is (0) start device.
br-lan 00:B0:52:00:00:01 Write /lib/firmware/plc/user.pib.old (0) (00200000:1077411840)
amphost: WriteExecutePIB can't read /lib/firmware/plc/user.pib.old …

Fix amphost PIB read error

---

ether/readpacket.c
serial/serial.c

- Include `poll.h` at the top of `ether/readpacket.c` to avoid nested
declaration errors caused by fortify source headers
- Add missing `sys/select.h` include to `serial/serial.c`
Signed-off-by: Jo-Philipp Wich <jow@openwrt.org>

open-plc-utils: fix musl and fortify source compatibility

---

plc/plcboot.c
plc/plchost.c
plc/plchostd.c
plc/plchostd2.c
plc/plctool.c

This patch should fix the failure (issue #49) during flash firmware into the QCA7000 with plcboot.

Fix issue #49 - unable to flash firmware into QCA7000 with plcboot

---

make.def

Conditionally assign ROOTFS variable, fixes issue #61.

Conditionally assign ROOTFS variable

---

plc/NetworkInformation2.c

plcstat -m reported wrong TX/RX rates

NetworkInformation2: Add a missing little endian conversion

---

tools/checksum32.c

We recently discovered, that running plcID on our I2SE Duckbill
devices (ARM) failed with the following error:
plcID: ReadKey2 found bad NVM header checksum in device module 0
After investigating, we found that this is an alignment issue. The
problem is casting the void memory pointer to an uint32_t pointer
since the latter one must be aligned on ARM. See [1] for reference
with a pointer to the C spec (in short: such a cast is undefined
behaviour).
To fix this issue, always use memcpy (which does the right thing
in all cases) to copy the data to an aligned temporary location
and use this one for calculating the checksum.
While at, remove the 'register' decoration from the function
prototype - let the compiler do the job. Also drop the alternate
compiler path, this new implementation …

Fix checksum32 for platforms which require aligned memory access

---

plc/SetNMK.c

This prevents a compiler warning.
Signed-off-by: Michael Heimpold <mhei@heimpold.de>

SetNMK.c: remove unused variable declaration

---

plc/Attributes1.c
plc/Attributes2.c
plc/GetProperty.c
plc/ModuleCommit.c
plc/ModuleSession.c
plc/ModuleWrite.c
plc/SetProperty.c
plc/VersionInfo2.c
plc/WatchdogReport.c
plc/WriteExecuteApplet2.c
plc/WriteExecuteFirmware1.c
plc/WriteExecuteFirmware2.c
plc/WriteExecutePIB.c
plc/WriteExecuteParameters1.c
plc/WriteExecuteParameters2.c

Check confirmation MMEs for matching cookie/session-ID.

session cookie/ID check

---

plc/plc.c

Get a random cookie on OS supporting /dev/urandom instead of always the
same 0x78563412.

Randomize session cookie/ID

---

plc/GetProperty.c

A request field had the wrong size.
A confirm field wasn't interpreted as little endian.

getproperty: fix it for big endian

---

plc/NetInfo1.c
plc/NetInfo2.c

In order to keep the relation between response address and network(s)
we should prepend the OSA in stdout because the output of Confirm()
isn't always reliable (output could be silented or buffering issues could mix up the order).

NetInfo: Print OSA to stdout

---

serial/ptsctl.c

Use memmove() instead of memcpy() for overlapping memory regions.

Use memmove() instead of memcpy() for overlapping memory regions

---

ether/Makefile
make.def
mme/Makefile
nvm/Makefile
pib/Makefile
plc/Makefile
slac/Makefile

Since we install the binary programs to /usr/local hierarchy by default,
we should also use the /usr/local hierarchy for manpages and do not mess
with /usr/share/man directories which are usually managed by distributions.
This allows better tracking of user installed manpages and is a cleaner
approach in general.

 Change default manpage installation destination to /usr/local hierarchy

---

README

The compilation itself should normally be run without elevated privileges,
so split it from the install step.
While at, adjust some minor formatting issues.
Signed-off-by: Michael Heimpold <mhei@heimpold.de>

README: split make process into two steps (fixes #103)

---

mdio/.gitignore
mdio/Makefile
mdio/mdiogen.1
plc/coqos_man.1
plc/mdustats.1
plc/plc.1
slac/evse.1
slac/pev.1

Mostly typos which causes formatting errors. Spotted during building Debian packages by lintian checks.

Some minor fixes for several manpages

---

docbook/version.h.html
tools/version.c
tools/version.h

Build timestamps prevent reproducible builds [0].
[0] https://reproducible-builds.org/docs/timestamps/

drop build timestamp #define COMPILE

---

slac/evse.1
slac/evse.c
slac/pev.1
slac/pev.c
slac/slac.h

The QCA7000 firmware (or better: HomePlug Green PHY as such) does not provide rich possibilities for connection quality checks like other chipsets do. For example with QCA7500 it's possible to transfer some amount of data, then check the average data rate and use this value as connection quality indicator. As this is not possible with QCA7000, one possible indicator value could be the signal attenuation when both sides are SLAC capable.
This PR modifies the existings tools _evse_ and _pev_ to allow focusing on the sounding step only. In other words, it is possible to use the part of a complete SLAC session to determine the attenuation between two PLC peers without the overhead of changing NMK, waiting for QCA7000 reboots etc.
This is intended to be used e.g. in a test bed where this …

Allow to focus on exchanging soundings only during SLAC

---

pib/pibpeek1.c
pib/pibpeek2.c

This pull request improves modpib to explicitly show the security level:
```
$ ./modpib -v parameters.pib 
PIB 0-0 0 bytes
MAC CC:00:FF:FF:EE:EE
DAK 68:9F:07:4B:8B:02:75:A2:71:0B:0B:57:79:AD:16:30 (HomePlugAV)
NMK 50:D3:E4:93:3F:85:5B:70:40:78:4D:F8:15:AA:8D:B7 (HomePlugAV)
NID B0:F2:E6:95:66:6B:03
Security level 0
NET Qualcomm Atheros Enabled Network
MFG Qualcomm Atheros HomePlug AV Device
USR Qualcomm Atheros Enabled Product
CCo Auto
MDU N/A
```

Improve modpib to show security level explicit

---

plc/Traffic2.c
plc/amprate.c
plc/plcrate.1
plc/plcrate.c

This introduces the commmand line switch -s which allows to
fine-control the network traffic generation: it suppresses
the generation of "antiphon" traffic, i.e. RX traffic (from
remote peer to local one) and thus speed-ups network testing
scenarios. This flag is only used in combination with
-t flag (one-to-many case) - the many-to-many case (-T) is
not affected.
For this is (re-)uses a flag PLC_TXONLY which requires minor
changes in amprate to keep existing behaviour of amprate.
(this flag was not usable in amprate - so I guess it is ok).
Also the man page is updated for plcrate to document this new
parameter.
Signed-off-by: Michael Heimpold <michael.heimpold@i2se.com>

plcrate: introduce command line parameter -s

---

plc/Topology1.c
plc/Topology2.c
plc/int6kstat.1
plc/plcstat.1

In a switched network, i.e. when local powerline device(s) are not
connected directly to host, then using the Local Management Address
to determine the local devices might fail due to wrong or incomplete
forwarding by the switch.
In this case it would be desirable to address the local powerline
device directly which is not possible with both tools at the moment.
This patch fixes this issue by keeping current behaviour as much as
possible and also document it in the corresponding man pages.
Signed-off-by: Michael Heimpold <michael.heimpold@i2se.com>

plcstat/int6kstat: allow to query a powerline device for topology directly

---

README
ether/channel.c
ether/channel.h
ether/closechannel.c
ether/ether.h
ether/gethwaddr.c
ether/getifname.c
ether/hostnics.c
ether/openchannel.c
ether/pcapdevs.c
ether/readpacket.c
ether/sendpacket.c
plc/PLCHostBoot.c
plc/plc.c
plc/plcdevs.c
plc/plchostd.c
plc/plchostd2.c
serial/int6kbaud.c
serial/int6kuart.c
serial/openport.c
serial/ptsctl.c
serial/weeder.c
tools/endian.h
tools/flags.h
tools/types.h

Add FreeBSD support. In most cases, this was just adding a "|| defined (__FreeBSD__)" next to existing BSD related compile checks.
Add a few missing parenthesis around some macro bodies, which were noticed by the default FreeBSD clang compiler.
Switch the bpf_length to unsigned, instead of signed. The BPF man page for all supported OSes indicates it should be unsigned, and as a buffer length, unsigned makes the most sense.
Fixes #122.

Add FreeBSD support, as well as fix a few bugs found while compiling in FreeBSD

---

plc/plc.h

Drop plcproperty from plc/plc.h to avoid the following build failure with gcc 10 (which defaults to -fno-common):
```
/home/buildroot/autobuild/run/instance-3/output-1/host/lib/gcc/arm-buildroot-linux-gnueabihf/10.2.0/../../../../arm-buildroot-linux-gnueabihf/bin/ld: rules.o:(.bss+0x0): multiple definition of `plcproperty'; pibruin.o:(.bss+0x0): first defined here
```
Fixes:
- http://autobuild.buildroot.org/results/6b3064b64dea3d4aaf219f787429c25918101483
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

plc/plc.h: fix build with gcc 10

---

slac/evse.ini
slac/evse_cm_slac_param.c

I wasn't able to use the demo SLAC procedure implemented in `evse.c` with a real ECU. It turns out at least this *big* name EVCC implementation requires the `CM_SLAC_PARAM.CNF` MME to exactly comply with the table A.2 provided in ISO 15118-3. This involves:
- Setting FORWARDING_STA to the EV HLE address
- Setting RESP_TYPE, NUM_SOUNDS, and TIME_OUT to the values indicated in the std. (1, 10, 6 resp.)

Fixed the EVSE CM_SLAC_PARAM.CNF response to match the ISO 15118-3 standard

---

plc/PLCNetworkInfo.c
plc/PLCPhyRates.c
plc/PLCTopology.c
plc/Platform.c
plc/VersionInfo1.c
plc/VersionInfo2.c
plc/WaitForStart.c
plc/chipset.c
plc/chipset.h
plc/plc.h

As described in #151, reporting the chipset name is not working as expected - at least as I would expect.
This PR tries solves this issue by introducing a new function which not only considers the MCLASS field
as older chipsetname function does, but by relying on the IDENT field in the response MME.
Signed-off-by: Michael Heimpold <michael.heimpold@in-tech.com>

Fix chipset reporting (fixes #151)

---

tools/types.h

Instead of trying to deal with bool stuff ourselv, just rely on the stdbool.h and use it instead.
This fixes compilation with gcc 15 as reported in #187.

tools/types.h: drop bool mess - include stdbool.h instead
